name: Flutter Build APK

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushs vers la branche principale.

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise l'environnement Ubuntu.

    steps:
      # 1. Checkout du code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configuration de Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # Utilise Eclipse Temurin pour Java.
          java-version: '17'        # Version de Java requise.

      # 3. Configuration de Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      # 4. Vérification de la version Java
      - name: Verify Java Version
        run: java -version

      # 5. Accepter les licences SDK Android
      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      # 6. Installer les dépendances Flutter
      - name: Flutter Pub Get
        run: flutter pub get

      # 7. Nettoyer le projet Flutter
      - name: Flutter Clean
        run: flutter clean

      # 8. Construire l'APK en mode release
      - name: Build APK
        run: flutter build apk --release

      # 9. Télécharger l'APK généré en tant qu'artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
